=== Hadi-Fooladi/EasyTCP/Source/EasyTCP.xsd
<schema
	version="5.0"
	xmlns:EasyTCP="EasyTCP"
	targetNamespace="EasyTCP"
	elementFormDefault="qualified"
	xmlns="http://www.w3.org/2001/XMLSchema">

	<element name="EasyTCP">
		<complexType>
			<sequence>
				<element name="DataType" type="EasyTCP:DataType" minOccurs="0" maxOccurs="unbounded" />

				<!-- Stream -->
				<element name="Stream">
					<complexType>
						<sequence>

							<!-- Packet -->
							<element name="Packet" minOccurs="0" maxOccurs="unbounded">
								<complexType>
									<complexContent>
										<extension base="EasyTCP:Base">
											<sequence>
												<element name="Data" type="EasyTCP:Field" minOccurs="0" maxOccurs="unbounded" />
											</sequence>

											<!-- Packet Attributes -->
											<attribute name="Code" type="int" use="required" />
										</extension>
									</complexContent>
								</complexType>
							</element>
						</sequence>

						<!-- Stream Attributes -->
						<attribute name="Version" type="string" use="required" />
						<attribute name="ClassName" type="string" use="required" />
					</complexType>
				</element>

				<element name="DataType" type="EasyTCP:DataType" minOccurs="0" maxOccurs="unbounded" />
			</sequence>

			<!-- EasyTCP Attributes -->
			<attribute name="Version" type="string" use="required" />
		</complexType>
	</element>

	<simpleType name="YesNo">
		<restriction base="string">
			<enumeration value="Yes"/>
			<enumeration value="No"/>
		</restriction>
	</simpleType>

	<complexType name="Base">
		<attribute name="Name" type="string" use="required" />
		<attribute name="Desc" type="string" use="optional" />
	</complexType>

	<complexType name="Field">
		<complexContent>
			<extension base="EasyTCP:Base">
				<attribute name="Type" type="string" use="required" />
				<attribute name="isList" type="EasyTCP:YesNo" use="optional" />
			</extension>
		</complexContent>
	</complexType>

	<complexType name="DataType">
		<complexContent>
			<extension base="EasyTCP:Base">
				<sequence>
					<element name="Field" type="EasyTCP:Field" minOccurs="0" maxOccurs="unbounded" />
				</sequence>

				<!-- DataType Attributes -->
				<attribute name="Partial" type="EasyTCP:YesNo" use="optional" />
				<attribute name="isClass" type="EasyTCP:YesNo" use="optional" />
			</extension>
		</complexContent>
	</complexType>
</schema>

=== Hadi-Fooladi/EasyTCP/Source/EasyTCP/SimpleMessenger/EasyTCP/MyStream.xml
<EasyTCP
	Version="1.0"
	ClassName="MyStream"
	xmlns="EasyTCP"
	xsi:schemaLocation="EasyTCP ../../../EasyTCP.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

	<Packet Code="0" Name="Info">
		<Data Name="Name" Type="string" />
	</Packet>

	<Packet Code="1" Name="Message">
		<Data Name="Message" Type="string" />
	</Packet>

	<Packet Code="2" Name="PicHeader">
		<Data Name="id" Type="long" />
		<Data Name="SegmentCount" Type="int" />
	</Packet>

	<Packet Code="3" Name="PicSegment">
		<Data Name="id" Type="long" />
		<Data Name="Num" Type="int" />
		<Data Name="Data" Type="ByteArray" />
	</Packet>
</EasyTCP>
